### PR TITLE
Story/TP-17814

### PR DESCRIPTION
**Pull request by daryn**
Formats context fields so kibana and loggly don't blow up when parsing the json.  Converts structs to a hash and json encodes arrays.

### CODE REVIEW

**Comment by jsturek** [comment]
Reviewing...

**Comment by jeffutter** [comment]
Reviewing

**Comment by jeffutter** [comment]
Something in the test output is printing to the terminal:

```
Hedgelog::Normalizer
  #normalize
{:message=>"dummy=1234"}
    returns the normalized data
    does not modify external state
  #normalize_hash
    returns a normalized hash
  #normalize_struct
{:foo=>1234, :bar=>"dummy"}
    returns struct as a normalized hash
  #normalize_array
["dummy string",{"message":"dummy=1234"}]
    returns array as a json string
  When a hash contains different types of data
{:message=>"dummy=1234", :hash=>{:message=>"dummy=1234"}, :struct=>{:foo=>1234, :bar=>"dummy"}, :array=>"[\"dummy string\",{\"message\":\"dummy=1234\"}]", :string=>"dummy", :number=>1234}
    normalizes recursively```

Might need to make sure you are setting the log dev to /dev/null

**Comment by jeffutter** [comment]
This looks good to me. We'll probably want to revisit performance at some time. However it is only really bad when doing nested things in debug mode, which is somewhat expected.

**Comment by jsturek** [comment]
Look good.

**Pull request merged**
